# Agile Learning Problem Elicitation (ALPE) framework: Educational technology and N-of-1 reproducible trial among physicians


Guilherme Isaac Schreiber Litwinski  
Guilherme Cunha  
João Ricardo Vissoci  
Bruno Melo  
Ricardo Pietrobon



<!--

communicate through wechat??? http://dev.wechat.com/wechatapi
incentive through the use of information from previous questions, even if repeated??
json
key taxonomy
copyright issues vs present info from page
databases for most common topics
present links
infographics
useful even if not complete answer?

https://telegram.org/
 -->

<!-- http://transag.sourceforge.net/ -->

## Abstract



## Introduction

Despite its best intentions, Healthcare Learning Technologies have been plagued by solutions that address either (1) what educators think it is important for healthcare professionals to learn or (2) what technologists are able to deliver. In contrast with these top approaches, technologies should be delivered with a focus on solving real problems from healthcare professionals. To our knowledge, however, no previous comprehensive framework has been described to date that might elicit information needs during a regular daily clinical practice.

* Learning problem elicitation methods among healthcare professionals
* Agile and its focus on stakeholders through iterative cycles

The objective of this study is therefore to describe an implementation of the Agile Learning Problem Elicitation (ALPE) framework, specifically describing its process, technology, analysis and reporting among neurologists. A further description is provided on how this framework could be coupled with N-of-1 trials to validate learning technologies that might address the problems emerging from ALPE.


## Methods


### Trial design

* N-of-1
* Intervention on Mondays, Wed and Fridays
* washout on Tuesdays, Thursdays and over the weekend
* No run-in necessary as participants were not recording their information needs in any form up to the start of the trial


### Ethics

* IRB approval, informed consent signed prior to the start of the trial


### Participants

* Two physicians, neurologist and general clinician, seeing patients in their daily practice. rounds, emergency room
* recruited through direct contact
* recording voice recorded notes about learning needs, e.g., "would like to know what differential diagnosis is", "what are alternative drugs for condition X"
* recordings did not contain any information about specific patients
* participants encouraged to take voice recording note at the very moment when needs arose



### Intervention


#### Daily diary arm 

* traditional method
* write down clinical questions that occurred during the day and where the participant felt the need to seek further information
* send them by email back to study coordination at the end of the day


#### Inbound arm


* [NetMemo Plus Voice Recorder](https://play.google.com/store/apps/details?id=com.netify.netmemopro&hl=en) or {{add iOS apps}}
    * recorded at the time the need arose
    * automatically submitted to study coordination through email
    * voice transcribed
    * questions answered using information available from the web
* transcript analysis using [RQDA](http://rqda.r-forge.r-project.org/) <!-- https://www.youtube.com/playlist?list=PL66CB2FF65368715C&feature=plcp -->


<!-- * feedback reporting tool
    * [Django](https://www.djangoproject.com/) framework
    * [Cerely](http://www.celeryproject.org/) task queueing
* weekly meeting with subject until reaches emergence saturation
 -->


#### Outcomes

* Number of information need events per day
* Emerging themes
	* transcription of information need in either voice recording or daily diary
	* tagging using RQDA in search of emerging themes
* Satisfaction with method scale at the end of each day
	* on a scale from 0 to 10, where 0 means not at all and 10 is absolutely, how satisfied are you with the method you are using to record your clinical information needs and obtain a response for them
* Change in practice
	* on a scale from 0 to 10, where 0 means not at all and 10 is absolutely, how much has your clinical practice changed as a result of this information needs gathering and corresponding responses today
* Knowledge perception in relation to daily topics 
	* on a scale from 0 to 10, where 0 means not at all and 10 is absolutely, how much has your knowledge about daily clinical facts changed as a function of the method you used to obtain responses today


### Sample size


<!-- might use a bayesian analysis, let's see -->

* Reproducible through scripts and links to preliminary data or relevant publications



### Stopping rules

Since this was an educational trial, the only stopping rule established for this trial was related to a possible privacy breach in relation to its data.


### Randomization

* Sequence generation delivered through email and SMS (WhatsApp and WeChat) in the morning of every Monday, Tuesday and Friday
* allocation concealment not possible
* blinding not possible


### Data analysis

* check crossdes
* Fully reproducible with corresponding scripts, assumption checking (carry-over effect, period effects, intra-subject correlation), efficacy evaluation, synthesis methods if more than one N-of-1 is being used (how heterogeneity between participants was assessed, [PRISMA guidelines](http://www.prisma-statement.org/))



### Semantic Reproducible Research protocol

<!-- grab from previous sections -->
<!-- |Reproducicle research|Scripts available on sites such as [Github](https://github.com/), data available on sites such as Github and [Figshare](http://figshare.com/), storage of software packages] -->

* data
* scripts
* [Rmd](https://github.com/rstudio/rmarkdown)
* software
* N-of-1 data compilation - [Use-case driven](http://www.researchgate.net/publication/221465095_A_Proposal_for_a_Unified_Process_for_Ontology_Building_UPON/file/79e4150a24778016df.pdf) [ontology](http://www.w3.org/RDF/) modeling which extends [Cook and Pietrobon, 2007](http://www.ncbi.nlm.nih.gov/pubmed/17847604), connection with R packages|



## Results

cunha 3546, isaac 76534

set.seed(); sample(c("daily_diary","inbound"), 30, replace = TRUE)



RQDA tables and graphics

## Discussion

* integration with N-of-1 trials
    * [AHRQ, 2014](http://effectivehealthcare.ahrq.gov/ehc/products/534/1844/n-1-trials-report-130213.pdf) 
    * [Personalized Lifelong Learning Consortium, 2014]() arXiv paper
    * Open edX and randomization framework Jacinto
